name: Tests on Rocky Linux 8

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  distribution-check:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
      options: --workdir=/home/build/hpc_lustreci
    steps:
    - uses: actions/checkout@v4
    - name: Install Deps
      run: |
        yum install -y sudo createrepo yum-utils dnf-plugins-core epel-release
        
    - name: Run Buil CentOS 8 latest
      run: |
         ./${{github.workdir}}/build_lustre_centos8_latest.sh
